# -*- coding: utf-8 -*-
"""aula1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aEDhgceTAld9QDs4B68wB5NtSGa9cV80

Instalação de bibliotecas
"""

"""Importar bibliotecas necessárias:"""

#arshkon/linkedin-job-postings

import os
import re
import json
import pandas as pd
import matplotlib.pyplot as plt
from kaggle.api.kaggle_api_extended import KaggleApi

kaggle_json = os.path.expanduser('~/.kaggle/kaggle.json')

try:
    with open(kaggle_json, 'r') as file:
        dados = json.load(file)
except FileNotFoundError:
    print("Arquivo não encontrado!")
except json.JSONDecodeError:
    print("JSON inválido!")

dados

# PASSO 3: Configurar variáveis de ambiente
os.environ['KAGGLE_USERNAME'] = dados['username']
os.environ['KAGGLE_KEY'] = dados['key']

try:
    api = KaggleApi()
    api.authenticate()
    print("Autenticação bem-sucedida !")

    # Teste
    print("\nSeus datasets:")
    print(api.dataset_list())

except Exception as e:
    print(f"❌ Erro: {e}")

dataset_name = "arshkon/linkedin-job-postings"  # Exemplo
download_path="/content/data"
api.dataset_download_files(dataset_name, path=download_path, unzip=True)

file_name="postings.csv"

df = pd.read_csv(f"{download_path}/{file_name}")

#pd.set_option('display.max_columns', None) # Mostrar todas as colunas
#pd.set_option('display.width', None) # Mostrar todas as linhas

print("✅ Arquivo carregado com sucesso!")
df.info()

df.head()
print("✅Primeiras 5 linhas do DataFrame:")
print(df.head())

df.describe()
print("✅ Estatísticas descritivas do DataFrame:")
print(df.describe())

# Função para calcular o percentual de valores nulos e zeros
def calculate_null_zero_percentage(df):
    total_values = df.size
    null_values = df.isnull().sum().sum()
    zero_values = (df == 0).sum().sum()
    
    null_percentage = (null_values / total_values) * 100
    zero_percentage = (zero_values / total_values) * 100
    
    return null_percentage, zero_percentage

# Calcular os percentuais de valores nulos e zeros no seu DataFrame
null_percentage, zero_percentage = calculate_null_zero_percentage(df)

print(f"Percentual de valores nulos: {null_percentage:.2f}%")
print(f"Percentual de valores zeros: {zero_percentage:.2f}%")